### PR TITLE
Guide step 7

### PR DESCRIPTION
**Pull request by cesarcneto**
Did not move forward with Apache Shiro integration due to this issue: https://github.com/vert-x3/vertx-auth/issues/32

### CODE REVIEW

**Comment by pmlopes** [comment]
@cesarcneto I'm trying to identify the issue, but i can't reproduce it, can you tell me what OS, Java Version are you using? and can you update this project to run and fail with the reported error so I can investigate what's going on with shiro?

**Comment by cesarcneto** [comment]
hey @pmlopes thanks for getting in touch. I'll do it today once I get home. Ok? Keep you posted.

**Comment by pmlopes** [comment]
@cesarcneto no need! I've fixed the issue in the shiro auth last friday. You can ignore the logged exception on the test, or update your pom to use the current development snapshot binaries:

https://github.com/vert-x3/vertx-auth/pull/205

**Comment by cesarcneto** [comment]
Thanks a lot @pmlopes!

**Pull request merged**
